name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, GitHub Actions!"

    - name: Run a multi-line script
      run: |
        echo "Starting script..."
        echo "Hello, this is running on Ubuntu!"
        echo "Script complete."

